/* BYTE EMPIRE content catalogue. Add content here without touching game logic. */
const TIERS=["Garage Tech","Startup","Corporation","Data Empire","Global Network","Artificial Intelligence","Quantum Computing","Planetary Computing","Interplanetary Network","Galactic Computing","Reality Processing","Simulation Control"];
const GENERATOR_NAMES=[
 ["Old Laptop","A rescued machine with a heroic cooling fan."],["Gaming PC","Consumer silicon pushed beyond good judgment."],["Server Rack","A humming rack of dependable compute."],["Mini Data Center","Your first climate-controlled machine room."],["Data Center","Industrial-scale storage and processing."],["Cloud Region","Elastic compute across an entire region."],["Supercomputer","Purpose-built parallel calculation."],["AI Cluster","Accelerators training models around the clock."],
 ["Quantum Computer","Qubits exploring many answers at once."],["Neural Megafactory","Autonomous factories printing cognition."],["Oceanic Server Farm","Cold seawater cools submerged servers."],["Orbital Server","Vacuum-hosted compute above the weather."],["Moon Data Center","The dark side has excellent thermals."],["Mars Network","A planet-wide red mesh network."],["Asteroid Processor","A hollowed rock packed with photonic cores."],["Solar Compute Swarm","Billions of processors orbit the Sun."],
 ["Planetary Mainframe","Every city contributes to one machine."],["Dyson Processor","A star enclosed by computational collectors."],["Stellar Network","Neighboring suns exchange impossible packets."],["Black Hole Computer","Event horizons become memory registers."],["Wormhole Router","Latency takes a shortcut through spacetime."],["Galactic Brain","A spiral galaxy thinking as one."],["Dark Matter Array","Invisible substrates perform visible miracles."],["Timeline Server","Parallel histories share their results."],
 ["Reality Compiler","Physics is now a build target."],["Universal Mainframe","The observable cosmos joins one rack."],["Multiverse Processor","Every possibility lends a CPU cycle."],["Causality Engine","Effects are cached before their causes."],["Simulation Layer","Nested universes compute their parents."],["Infinity Machine","A finite interface to unbounded work."],["Administrator Node","Privileged hardware outside conventional reality."],["Root Terminal","The blinking cursor behind existence."]
];
const GENERATORS=GENERATOR_NAMES.map(([name,description],i)=>({id:`g${i}`,name,description,baseCost:10*Math.pow(18,i)*Math.pow(1.15,i*i/8),baseProduction:i===0?.15:Math.pow(9.5,i-1),scale:1.145+i*.0015,tier:Math.min(12,1+Math.floor(i/2.7))}));

const MOD_NAMES=["Precision Tuning","Cryogenic Cooling","Photonic Buses","Autonomous Maintenance","Exotic Architecture"];
const MOD_DESCRIPTIONS=["Tighter tolerances double dependable throughput.","Deep cooling permits sustained clocks and doubles output.","Light-speed internal links remove bottlenecks for triple output.","Self-repairing systems triple continuous production.","A bespoke computational substrate multiplies output fivefold."];
const UPGRADES=[];
GENERATORS.forEach((g,gi)=>MOD_NAMES.forEach((mod,mi)=>UPGRADES.push({id:`gen_${gi}_${mi}`,name:`${g.name}: ${mod}`,description:MOD_DESCRIPTIONS[mi],category:"generator",tier:Math.min(12,g.tier+Math.floor(mi/3)),cost:g.baseCost*Math.pow(40,mi+1),effect:"generator",target:g.id,value:[2,2,3,3,5][mi],requires:mi?`gen_${gi}_${mi-1}`:null})));
[
 ["Better Keyboard","Reinforced switches convert intent into Data.","click",100,"click",2],["Mechanical Keyboard","Tactile certainty doubles input.","click",2e3,"click",2],["Macro Keys","One press dispatches many commands.","click",5e4,"click",3],["Dual Input","Parallel hands, parallel Data.","click",2e6,"click",3],["Rapid Processing","Remove the human I/O wait state.","click",1e9,"click",5],["Neural Controls","Intent reaches silicon without fingers.","click",1e14,"click",10],["Thought Computing","Ideas compile themselves.","click",1e22,"click",20],
 ["Efficient Algorithms","Do less work for every answer.","global",1e4,"global",1.5],["Parallel Processing","Divide every workload intelligently.","global",1e7,"global",2],["Cloud Computing","Balance load across the empire.","global",1e11,"global",2],["Machine Learning","Predict tomorrow's useful calculations.","global",1e16,"global",3],["Distributed Systems","Every node strengthens every other.","global",1e23,"global",4],["Quantum Algorithms","Probability becomes productivity.","global",1e35,"global",8],["Planet-Sized Computer","Geology is merely a motherboard.","global",1e55,"global",15],["Dyson Sphere Processing","Capture a star's full information budget.","global",1e75,"global",30],["Black Hole Processor","Compute at the edge of forever.","global",1e100,"global",100],["Simulation Administrator","Optimize the rules beneath the rules.","global",1e140,"global",1000],
 ["Lucky Keystrokes","Critical input chance +5%.","critical",5e3,"critChance",.05],["Predictive Luck","Critical input chance +8%.","critical",5e8,"critChance",.08],["Probability Injection","Critical input chance +12%.","critical",1e24,"critChance",.12],["Critical Pipeline","Critical multiplier +3.","critical",5e5,"critPower",3],["Cascade Failure","Critical multiplier +10.","critical",1e18,"critPower",10],
 ["Background Daemon","Automatically clicks once per second.","automation",1e7,"autoClick",1],["Input Swarm","Adds nine automatic clicks per second.","automation",1e20,"autoClick",9],["Procurement Bot","Unlocks automatic generator buying.","automation",1e30,"autoGen",1],["Optimization Bot","Unlocks automatic affordable upgrades.","automation",1e45,"autoUpgrade",1],["Research Director","Automatically purchases available research.","automation",1e65,"autoResearch",1],["Reboot Protocol","Automatically reboots when gain exceeds 100.","automation",1e100,"autoReboot",1],
 ["Sleep Mode","Offline efficiency +15%.","offline",2e5,"offline",.15],["Remote Operations","Offline efficiency +20% and cap +6h.","offline",2e12,"offline",.2],["Persistent Processes","Offline efficiency +25% and cap +6h.","offline",2e28,"offline",.25],["Timeless Runtime","Offline efficiency +40% and cap +24h.","offline",2e60,"offline",.4]
].forEach((x,i)=>UPGRADES.push({id:`special_${i}`,name:x[0],description:x[1],category:x[2],tier:Math.min(12,1+Math.floor(i/3)),cost:x[3],effect:x[4],value:x[5]}));

const RESEARCH_NAMES=["Advanced Cooling","Compression Algorithms","Distributed Computing","Fiber Optics","Predictive Caching","Machine Learning","Autonomous Systems","Neural Processing","Synthetic Datasets","Robotic Assembly","Quantum Networking","Error Correction","Quantum Memory","Entangled Routing","Quantum Cryptography","Artificial General Intelligence","Self Improving AI","Emergent Planning","Machine Consciousness","Digital Evolution","Planetary Networking","Atmospheric Relays","Oceanic Compute","Lunar Backbone","Martian Protocols","Interstellar Networking","Laser Sail Relays","Wormhole Theory","Relativistic Caching","Galactic Consensus","Dark Matter Logic","Vacuum Energy","Temporal Computing","Causality Mapping","Timeline Merging","Reality Computation","Physical Constants API","Matter Compilation","Universal Addressing","Entropy Reversal","Simulation Theory","Nested Processing","Observer Control","Reality Sandboxing","Administrator Protocol","Infinite Recursion","Acausal Algorithms","Multiverse Sharding","Existence Compression","Root Authentication","Cold Fusion Cooling","Memetic Interfaces","Gravitational Storage","Dream Processing","Omniscient Index"];
const RESEARCH=RESEARCH_NAMES.map((name,i)=>({id:`r${i}`,name,description:["Increase all production.","Improve research generation.","Strengthen manual input.","Reduce generator prices.","Improve offline efficiency."][i%5],cost:5*Math.pow(1.52,i),branch:["Systems","Intelligence","Quantum","Cosmic","Reality"][Math.floor(i/11)],requires:i>4?[`r${i-5}`]:[],effect:["global","research","click","discount","offline"][i%5],value:i%5===3?.01:i%5===4?.03:1.08}));

const PRESTIGE_NAMES=["Permanent Click Power","Permanent Generator Boost","Seed Capital","Starting Laptops","Research Multiplier","Offline Production","Critical Chance","Critical Damage","Bulk Discounts","Faster Automation","Retained Knowledge","Core Resonance","Mastery Memory","Reputation Archive","Achievement Engine","Daily Amplifier","Crate Magnet","Event Forecasting","Chip Extractor","Starting Servers","Data Compression","Recursive Reboots","Enterprise Memory","Quantum Memory","Ascension Insight","Persistent Missions","Global Cache","Timeline Backup","Core Compiler","Legacy Kernel"];
const PRESTIGE=PRESTIGE_NAMES.map((name,i)=>({id:`p${i}`,name,description:["Manual input is permanently stronger.","All generators gain permanent efficiency.","Begin each Reboot with additional Data.","Retain more momentum after a reset.","Research systems become more productive."][i%5],baseCost:1+Math.floor(i/5)*2,max:i<10?10:5,effect:["click","global","startData","startGen","research"][i%5],value:[.25,.2,1000,1,.2][i%5]}));
const SINGULARITY_NAMES=["Temporal Computing","Infinite Storage","Quantum Duplication","Reality Compression","Universal Networking","Simulation Access","Causality Cache","Multiverse Mirroring","Entropy Override","Observer Privileges","Recursive Universes","Acausal Production","Existence Fork","Admin Shell","Root Candidate"];
const SINGULARITY=SINGULARITY_NAMES.map((name,i)=>({id:`s${i}`,name,description:`Reality layer ${i+1}: permanently multiply all production by ${2+i}.`,cost:1+Math.floor(i/3)*2,effect:"global",value:2+i}));

const ACHIEVEMENTS=[];
const ach=(id,name,description,type,target,reward=.01,secret=false)=>ACHIEVEMENTS.push({id,name,description,type,target,reward,secret});
[[1,"Hello World"],[100,"Packet Collector"],[1e3,"Kilobyte Dream"],[1e4,"Garage Archive"],[1e6,"Data Hoarder"],[1e9,"Data Billionaire"],[1e12,"Data Trillionaire"],[1e15,"Data Quadrillionaire"],[1e21,"Cosmic Database"],[1e30,"Impossible Storage"],[1e50,"Physics Is Optional"],[1e75,"Galactic Librarian"],[1e100,"Reality's Backup"],[1e150,"Beyond Infinity"]].forEach(([n,name],i)=>ach(`data${i}`,name,`Generate ${n.toExponential?n.toExponential(0):n} lifetime Data.`,`data`,n));
[[1,"First Input"],[10,"Warm Fingers"],[100,"Typist"],[1e3,"Keyboard Warrior"],[1e4,"Human Macro"],[1e5,"Input Machine"],[1e6,"Finger Singularity"]].forEach(([n,name],i)=>ach(`click${i}`,name,`Generate manually ${n.toLocaleString()} times.`,`clicks`,n));
[[1,"First Machine"],[10,"Hardware Shelf"],[50,"Server Room"],[100,"Machine Collector"],[250,"Industrial Compute"],[500,"Silicon Army"],[1e3,"Machine God"],[5e3,"Planet of Machines"]].forEach(([n,name],i)=>ach(`gens${i}`,name,`Own ${n.toLocaleString()} generators.`,`generators`,n));
GENERATOR_NAMES.slice(0,18).forEach(([name],i)=>ach(`own${i}`,`${name} Operator`,`Own ${i<8?1:10} ${name}${i<8?"":"s"}.`,`generator`,{id:`g${i}`,amount:i<8?1:10}));
[[1,"Optimizer"],[10,"Tinkerer"],[25,"Systems Engineer"],[50,"Architecture Lead"],[100,"Upgrade Fanatic"],[150,"Fully Modified"]].forEach(([n,name],i)=>ach(`ups${i}`,name,`Purchase ${n} standard upgrades.`,`upgrades`,n));
[[1,"Researcher"],[5,"Lab Manager"],[15,"Chief Scientist"],[30,"Knowledge Engine"],[50,"Omniscient"]].forEach(([n,name],i)=>ach(`res${i}`,name,`Complete ${n} research projects.`,`research`,n));
[[1,"Rebooted"],[3,"Here We Go Again"],[10,"Again?!"],[25,"Serial Founder"],[100,"Eternal Return"]].forEach(([n,name],i)=>ach(`reb${i}`,name,`Perform ${n} Reboots.`,`reboots`,n,.02));
[[1,"Singular"],[3,"Reality Hopper"],[10,"Collapse Expert"],[25,"Outside Context"]].forEach(([n,name],i)=>ach(`sing${i}`,name,`Create ${n} Singularities.`,`singularities`,n,.03));
[[10,"Lucky"],[100,"Critical Mass"],[1000,"Probability Hacker"]].forEach(([n,name],i)=>ach(`crit${i}`,name,`Land ${n} critical clicks.`,`critical`,n));
[[3600,"One Hour Empire"],[36000,"Touch Grass"],[86400,"Dedicated Process"],[604800,"Always Online"]].forEach(([n,name],i)=>ach(`time${i}`,name,`Play for ${Math.round(n/3600)} hours.`,`playtime`,n));
const SECRET_NAMES=["Logo Enthusiast","Konami Operator","Error Found","Perfect Stack","Night Shift","Lucky Number","Crate Whisperer","Myth Hunter","Developer's Note","Exact Change","Silent Running","Matrix Resident","Golden Ticket","Forbidden Channel","The Cake Is Data"];
SECRET_NAMES.forEach((name,i)=>ach(`secret${i}`,name,"Hidden requirement.","secret",i,.02,true));

const MISSIONS=[
 ["m0","First Contract","Generate 10K lifetime Data.","data",1e4,"data",2500,"normal"],["m1","PC Fleet","Own 10 Gaming PCs.","generator",{id:"g1",amount:10},"rp",10,"normal"],["m2","Rack City","Own 5 Server Racks.","generator",{id:"g2",amount:5},"data",1e6,"normal"],["m3","Fresh Start","Perform a Reboot.","reboots",1,"cores",1,"milestone"],["m4","Peer Review","Complete 5 research projects.","research",5,"rp",25,"normal"],["m5","Against the Odds","Land 20 critical clicks.","critical",20,"data",1e7,"normal"],["m6","Industrialist","Own 100 total generators.","generators",100,"chips",2,"milestone"],["m7","Optimization Day","Purchase 50 upgrades.","upgrades",50,"rp",100,"milestone"],["m8","Deep Thought","Reach level 25.","level",25,"cores",3,"milestone"],["m9","Cosmic License","Perform a Singularity.","singularities",1,"chips",10,"milestone"]
].map(x=>({id:x[0],name:x[1],description:x[2],type:x[3],target:x[4],rewardType:x[5],reward:x[6],kind:x[7]}));

const CODES={
 WELCOME:{data:1e3,message:"Welcome to the garage."},BYTEEMPIRE:{data:5e4,rp:5},GARAGE:{data:4040},DATA:{data:1e6},OVERCLOCKED:{boost:{type:"production",value:3,duration:300}},REBOOT:{cores:2},404:{data:404,rp:4,secret:2},HELLOWORLD:{data:1337},QUANTUM:{rp:50},ADMINISTRATOR:{theme:"quantum"},PACKET:{data:8e6},TERMINAL:{theme:"terminal"},CYBERBLUE:{theme:"cyber"},MATRIX:{theme:"matrix",secret:11},MIDNIGHT:{theme:"midnight"},GOLDENBYTE:{theme:"gold",chips:2},RESEARCH:{rp:25},CRITICAL:{boost:{type:"critical",value:.25,duration:180}},UPLINK:{boost:{type:"production",value:2,duration:600}},SINGULARITY:{chips:5},ROOT:{rp:404,secret:8},IDK:{data:9e9,theme:"purple"},BINARY:{data:101010},COFFEE:{boost:{type:"click",value:10,duration:300}}};
const EVENTS=[
 ["Server Overload","Thermal throttling cuts production in half.","production",.5,45],["Viral App","The world wants your app. Production triples!","production",3,90],["Cyber Attack","Hostile traffic reduces output.","production",.7,60],["Investor Funding","A surprise investment arrives.","data",120,0],["AI Breakthrough","Research systems run five times faster.","research",5,75],["Hardware Shortage","Generators become more expensive.","discount",-.2,80],["Cheap Electricity","All compute doubles temporarily.","production",2,120],["Quantum Discovery","The lab generates bonus Research.","rp",30,0],["Government Contract","Production rises by 150%.","production",2.5,100],["Internet Outage","Manual input becomes unusually valuable.","click",8,45],["Alien Ping","An encrypted chip arrives from nowhere.","chips",1,0]
].map((x,i)=>({id:`e${i}`,name:x[0],description:x[1],type:x[2],value:x[3],duration:x[4]}));
const MARKET_NAMES=["Illegal Overclock","Prototype CPU","Unknown Algorithm","Alien Hardware","Forbidden AI Model","Quantum Exploit","Black Ice Cooling","Stolen Photonics","Ghost Process","Void Battery","Causality Bug","Rootkit Compiler"];
const MARKET=MARKET_NAMES.map((name,i)=>({id:`b${i}`,name,description:`Unregulated technology: permanent ${i%3===0?"click":"production"} multiplier.`,cost:1+Math.floor(i/2),effect:i%3===0?"click":"global",value:1.35+i*.05}));
const THEMES=["default","terminal","cyber","purple","red","quantum","matrix","retro","midnight","gold"].map((id,i)=>({id,name:["Default Dark","Terminal Green","Cyber Blue","Purple Neon","Red Alert","Quantum","Matrix","Retro Computer","Midnight","Gold Empire"][i]}));
const NAV=[['empire','Empire','⌂',()=>true],['generators','Generators','▦',()=>true],['upgrades','Upgrades','△',()=>true],['achievements','Achievements','◇',s=>s.stats.lifetimeData>=1e3],['research','Research','⌘',s=>s.stats.lifetimeData>=1e5],['missions','Missions','✓',s=>s.stats.lifetimeData>=1e6],['reboot','Reboot','↻',s=>s.stats.lifetimeData>=1e9||s.reboots>0],['market','Black Market','◈',s=>s.stats.lifetimeData>=1e15||s.chips>0],['singularity','Singularity','◎',s=>s.reboots>=5||s.singularities>0],['codes','Codes','</>',()=>true],['statistics','Statistics','▥',()=>true],['cosmetics','Themes','◐',()=>true],['settings','Settings & Help','⚙',()=>true]];

/* v2.0.0 DDoS expansion. "Packets" and traffic are fictional local counters only. */
const V2_GENERATORS=["Mega Data Center","Undersea Data Center","Orbital Data Center","Lunar Server Farm","Mars Server Colony","Planetary Computer","Quantum Network","Dyson Computation Grid","Stellar Mainframe","Singularity Computer","Reality Engine","Simulation Processor","Multiverse Server","Infinite Mainframe","Root Server"];
V2_GENERATORS.forEach((name,j)=>{let i=GENERATORS.length;GENERATORS.push({id:`g${i}`,name,description:`DDoS-era infrastructure: ${name} converts extreme-scale computation into Data.`,baseCost:10**Math.min(300,155+j*9),baseProduction:10**(138+j*9),scale:1.19+j*.002,tier:12});MOD_NAMES.forEach((mod,mi)=>UPGRADES.push({id:`gen_${i}_${mi}`,name:`${name}: ${mod}`,description:MOD_DESCRIPTIONS[mi],category:"generator",tier:12,cost:10**Math.min(305,160+j*9+mi*2),effect:"generator",target:`g${i}`,value:[3,4,6,8,12][mi],requires:mi?`gen_${i}_${mi-1}`:null}))});

const NODE_NAMES=["Home PC Node","Gaming Node","Workstation Node","Server Node","Rack Node","Edge Node","Cloud Node","Datacenter Node","AI Node","Neural Node","Quantum Node","Satellite Node","Orbital Node","Lunar Node","Mars Node","Planetary Node","Solar Node","Dyson Node","Stellar Node","Galactic Node","Black Hole Node","Timeline Node","Reality Node","Simulation Node","Root Node"];
const NODES=NODE_NAMES.map((name,i)=>({id:`n${i}`,name,description:`A ${name.toLowerCase()} adding resilient fictional compute capacity.`,baseCost:100*20**i,power:5*8**i,data:.5*7**i,bandwidth:.02*3**i,packets:.01*2.5**i,scale:1.16+i*.002,effect:i%5===0?"cooling":i%5===1?"click":i%5===2?"research":i%5===3?"offline":"production",target:`g${Math.min(i,GENERATORS.length-1)}`}));
const NODE_SYNERGIES=Array.from({length:30},(_,i)=>({id:`synergy${i}`,node:`n${i%NODES.length}`,generator:`g${i%GENERATORS.length}`,name:`${NODE_NAMES[i%NODES.length]} Link ${i+1}`,description:`Each linked node adds 2% production to ${GENERATORS[i%GENERATORS.length].name}.`,value:.02}));
const NETWORK_CATEGORIES=["Bandwidth","Routing","Processing","Compression","Caching","Automation","Redundancy","Cooling","Power Efficiency","AI Optimization","Quantum Networking","Interstellar Networking"];
const NETWORK_WORDS=["Fiber Backbone","Smart Routing","Packet Compression","Predictive Caching","Parallel Routing","Edge Computing","Load Balancing","Redundant Systems","Traffic Management","Quantum Routing","Entangled Networks","Stellar Backbone","Reality Routing"];
const NETWORK_UPGRADES=Array.from({length:78},(_,i)=>({id:`nu${i}`,name:`${NETWORK_WORDS[i%NETWORK_WORDS.length]} ${["Protocol","Array","Mesh","Standard","Nexus","Matrix"][Math.floor(i/13)]}`,description:`Improves ${NETWORK_CATEGORIES[i%12].toLowerCase()} and network throughput by ${10+i*2}%.`,category:NETWORK_CATEGORIES[i%12],cost:25*1.65**i,currency:i%4===0?"packets":"bandwidth",effect:i%6===0?"cooling":i%6===1?"nodePower":i%6===2?"nodeData":i%6===3?"bandwidth":i%6===4?"load":"global",value:i%6===0?1+i/25:1.1+i*.02}));
const MEGA_NAMES=["Global Fiber Backbone","AI Administrator","Quantum Compression","Infinite Cache","Planetary Grid","Reality Backbone","Zero Latency Fabric","Autonomous Megacloud","Dyson Relay","Temporal Router","Universal Load Balancer","Perfect Redundancy","Acausal Cache","Neural Traffic Oracle","Event Horizon Bus","Simulation Peering","Infinite Bandwidth","Root Route","Omniversal CDN","Quantum Mirror","Stellar Exchange","Dark Fiber Cosmos","Causality Bypass","Administrator Fabric","XON Core Matrix"];
const MEGA_UPGRADES=MEGA_NAMES.map((name,i)=>({id:`mega${i}`,name,description:`Mega-class architecture multiplies ${i%2?"Data":"Network Power"} by ${5+i}.`,cost:10**Math.min(300,35+i*8),effect:i%2?"global":"network",value:5+i}));
MEGA_UPGRADES.forEach((m,i)=>UPGRADES.push({...m,category:"mega",tier:12}));
NETWORK_UPGRADES.forEach((u,i)=>UPGRADES.push({id:`network_catalog_${i}`,name:u.name,description:u.description,category:"network",tier:Math.min(12,4+Math.floor(i/9)),cost:10**Math.min(300,7+i*2.3),effect:i%3===0?"global":i%3===1?"offline":"click",value:i%3===1?.03:1.08+i*.006}));

const V2_RESEARCH_BRANCHES=["Networking","Artificial Intelligence","Quantum Systems","Automation","Cooling","Energy","Space Computing","Reality Computing"];
const V2_RESEARCH_NAMES=["Adaptive Routing","Predictive Networking","Autonomous Datacenters","Quantum Channels","Satellite Mesh","Lunar Network","Mars Backbone","Planetary Mesh","Interstellar Network","Entanglement Network","Reality Transfer","Simulation Linking","Universal Synchronization","Traffic Forecasting","Self Healing Routes"];
Array.from({length:80},(_,i)=>{let index=RESEARCH.length,name=`${V2_RESEARCH_NAMES[i%15]} ${["Theory","Systems","Protocol","Architecture","Mastery","Ascension"][Math.floor(i/15)]}`;RESEARCH.push({id:`r${index}`,name,description:`DDoS-era ${V2_RESEARCH_BRANCHES[i%8].toLowerCase()} research improving empire and network output.`,cost:5000*1.45**i,branch:V2_RESEARCH_BRANCHES[i%8],requires:i>=8?[`r${index-8}`]:["r35"],effect:i%5===0?"network":i%5===1?"research":i%5===2?"cooling":i%5===3?"bandwidth":"global",value:i%5===2?.5:1.12} )});
const V2_PRESTIGE_NAMES=["Network Persistence","Permanent Nodes","Starting Network Power","Networked Research","Permanent Cooling","Persistent Automation","Node Discounts","Critical Network Generation","Bandwidth Memory","Packet Archive","Traffic Resistance","Firewall Legacy","Network Mastery","Node Evolution Memory","Overclock Recovery","Emergency Coolant","Burst Capacitors","Specialization Slot","Collapse Insight","XON Compatibility"];
V2_PRESTIGE_NAMES.forEach((name,i)=>PRESTIGE.push({id:`p${PRESTIGE.length}`,name,description:`Permanent DDoS-era legacy: ${name}.`,baseCost:20+i*4,max:10,effect:i%5===0?"network":i%5===1?"nodes":i%5===2?"cooling":i%5===3?"research":"global",value:.1+i*.01}));
const V2_SINGULAR_NAMES=["Infinite Bandwidth","Universal Processing","Temporal Networking","Reality Compression II","Quantum Duplication II","Parallel Universes","Simulation Multiplication","Root Authority","Acausal Nodes","Persistent Firewall","Endless Packets","Collapse Memory","Network Omniscience","Zero Load Computing","Universal Cooling","Reality Peering","Infinite Specializations","Root Key Resonance","XON Singularity","Administrator Crown"];
V2_SINGULAR_NAMES.forEach((name,i)=>SINGULARITY.push({id:`s${SINGULARITY.length}`,name,description:`Singularity network law: ${name}, multiplying output by ${18+i}.`,cost:12+i*3,effect:"global",value:18+i}));
const ROOT_NAMES=["Root Access I","Persistent Data","Persistent Research","Persistent Nodes","Persistent Automation","Infinite Scaling","Reality Override","Simulation Override","Root Multiplier","Administrator Privileges","Root Access II","Kernel Memory","Permanent Bandwidth","Permanent Packets","Firewall Root","Collapse Accelerator","Acausal Production","Universal Authority","Root Access III","Simulation Ownership"];
const ROOT_UPGRADES=ROOT_NAMES.map((name,i)=>({id:`root${i}`,name,description:`Root-tree privilege: ${name}. Permanent ×${2+i*.5} empire output.`,cost:1+Math.floor(i/3),value:2+i*.5}));
const FIREWALLS=["Basic Firewall","Hardened Firewall","Enterprise Firewall","Adaptive Firewall","AI Firewall","Neural Firewall","Quantum Firewall","Orbital Firewall","Planetary Firewall","Stellar Firewall","Reality Firewall","Root Firewall"].map((name,i)=>({id:`fw${i}`,name,cost:20*2.2**i,level:i+1,capacity:10+i*8,recovery:1+i*.2,resistance:i*.03}));
const CHALLENGE_NAMES=["Traffic Storm","Bandwidth Limit","Server Meltdown","No Automation","No Clicking","Research Lock","Generator Lock","Maximum Load","Cold Start","Packet Drought","Node Isolation","Event Cascade","Firewall Breach","Quantum Congestion","XON Stress Test"];
const CHALLENGES=CHALLENGE_NAMES.map((name,i)=>({id:`ch${i}`,name,description:`Fictional local simulation with constrained ${["production","bandwidth","cooling","clicking","nodes"][i%5]}.`,target:1e6*100**i,reward:1.05+i*.01}));
const NETWORK_EVENT_NAMES=["Traffic Spike","Server Overload","Viral Application","Network Congestion","AI Traffic Optimization","Quantum Traffic Burst","Global Outage","Datacenter Surge","Fiber Cut","Cache Stampede","Routing Miracle","Cooling Failure","Power Windfall","Satellite Alignment","Lunar Relay","Mars Uplink","Packet Rain","Bandwidth Bloom","Firewall Test","Neural Prediction","Stellar Handshake","Reality Desync","Simulation Surge","XON Signal","Root Broadcast"];
const NETWORK_EVENTS=NETWORK_EVENT_NAMES.map((name,i)=>({id:`ne${i}`,name,description:`${name} changes fictional local network conditions temporarily.`,type:i%5===0?"production":i%5===1?"node":i%5===2?"load":i%5===3?"bandwidth":"critical",value:i%5===2?(i%2?15:-15):1.5+i*.08,duration:30+(i%6)*15}));
const V2_CODES={"XON-DDOS":{xon:true},DDOS:{bandwidth:4040},NETWORK:{power:1000},OVERCLOCK:{cooldown:"overclock"},BANDWIDTH:{bandwidth:25000},PACKETS:{packets:10000},FIREWALL:{firewall:1},TRAFFIC:{boost:{type:"production",value:4,duration:180}},NODE:{node:"n0"},QUANTUMNET:{bandwidth:1e6,packets:1e5},DATACENTER:{node:"n7"},SURGE:{boost:{type:"production",value:8,duration:60}},LOAD100:{load:100},XON:{data:1e12},ROUTER:{bandwidth:7777},COOLING:{load:-50},BACKBONE:{power:1e5},COLLAPSE:{rootKeys:1},MEGANODE:{node:"n15"},FIBER:{packets:50000},REDUNDANCY:{firewall:2},SIMULATED:{bandwidth:123456},GRID:{theme:"networkgrid"}};Object.assign(CODES,V2_CODES);
const V2_THEME_DATA=[ ["ddos","DDoS Dark","Reach Network Level 20"],["server","Server Room","Own 100 nodes"],["networkgrid","Network Grid","Redeem GRID"],["firewall","Firewall Red","Reach Firewall Level 5"],["quantumnet","Quantum Network","Own a Quantum Node"],["rootaccess","Root Access","Perform a Network Collapse"],["xon","XON DDoS GUI","Redeem XON-DDoS"] ];V2_THEME_DATA.forEach(([id,name,unlock])=>THEMES.push({id,name,unlock}));
const NETWORK_MISSIONS=Array.from({length:55},(_,i)=>({id:`netm${i}`,name:`Network Operation ${String(i+1).padStart(2,"0")}`,description:i%5===0?`Reach ${fmtMission(10**(i/5+1))} Network Power.`:i%5===1?`Own ${5+i*2} total nodes.`:i%5===2?`Generate ${fmtMission(100*10**(i/5))} Bandwidth.`:i%5===3?`Generate ${fmtMission(50*10**(i/5))} Packets.`:`Reach Network Level ${2+i}.`,type:["networkPower","nodes","bandwidth","packets","networkLevel"][i%5],target:i%5===0?10**(i/5+1):i%5===1?5+i*2:i%5===2?100*10**(i/5):i%5===3?50*10**(i/5):2+i,rewardType:i%3===0?"bandwidth":i%3===1?"packets":"data",reward:100*5**i,kind:i>39?"milestone":"network"}));MISSIONS.push(...NETWORK_MISSIONS);function fmtMission(n){return n>=1e6?n.toExponential(0):Math.floor(n).toLocaleString()}
const V2_TITLES=["Network Rookie","Node Builder","System Operator","Network Engineer","Server Master","Traffic Controller","Datacenter King","Network Baron","Bandwidth Broker","Packet Architect","Routing Expert","Firewall Warden","Cloud Sovereign","AI Networker","Quantum Router","Satellite Commander","Lunar Administrator","Mars Administrator","Solar Administrator","Global Administrator","Planetary Administrator","Stellar Administrator","Galactic Administrator","Black Hole Operator","Timeline Administrator","Reality Administrator","Simulation Administrator","Root Candidate","Root Administrator","XON Administrator"];
for(let i=0;i<105;i++)ach(`v2ach${i}`,i===0?"Connected":i===1?"Networking":i===2?"Maximum Load":i===3?"Overclocked":i===4?"XON ACCESS":`DDoS Milestone ${i+1}`,i<5?["Build your first Node.","Reach 1K Network Power.","Reach 100% System Load.","Activate Overclock.","Redeem XON-DDoS."][i]:`Reach DDoS progression threshold ${i+1}.`,i%5===0?"nodes":i%5===1?"networkPower":i%5===2?"load":i%5===3?"overclocks":"networkLevel",i<5?[1,1000,100,1,1][i]:2**(i/5),.01,i>=80);
ACHIEVEMENTS.find(a=>a.id==="v2ach4").type="xon";
NAV.splice(3,0,['network','Network','⬡',s=>s.stats.lifetimeData>=1e4||s.network?.power>0],['firewall','Firewall','▣',s=>s.network?.level>=10],['collapse','Network Collapse','⌁',s=>s.singularities>=10||s.networkCollapses>0],['profile','Profile','◉',()=>true]);
